// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// GenCode is an autogenerated mock type for the GenCode type
type GenCode struct {
	mock.Mock
}

// GenerateCode provides a mock function with no fields
func (_m *GenCode) GenerateCode() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateCode")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewGenCode creates a new instance of GenCode. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGenCode(t interface {
	mock.TestingT
	Cleanup(func())
}) *GenCode {
	mock := &GenCode{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
