// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock_cache

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// DB is an autogenerated mock type for the DB type
type DB struct {
	mock.Mock
}

// DeleteCacheGroupKey provides a mock function with given fields: ctx, cacheGroupKey
func (_m *DB) DeleteCacheGroupKey(ctx context.Context, cacheGroupKey string) error {
	ret := _m.Called(ctx, cacheGroupKey)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCacheGroupKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, cacheGroupKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteCacheKey provides a mock function with given fields: ctx, cacheGroupKey, cacheKey
func (_m *DB) DeleteCacheKey(ctx context.Context, cacheGroupKey string, cacheKey string) error {
	ret := _m.Called(ctx, cacheGroupKey, cacheKey)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCacheKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, cacheGroupKey, cacheKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCacheData provides a mock function with given fields: ctx, cacheGroupKey, cacheKey
func (_m *DB) GetCacheData(ctx context.Context, cacheGroupKey string, cacheKey string) ([]byte, error) {
	ret := _m.Called(ctx, cacheGroupKey, cacheKey)

	if len(ret) == 0 {
		panic("no return value specified for GetCacheData")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]byte, error)); ok {
		return rf(ctx, cacheGroupKey, cacheKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []byte); ok {
		r0 = rf(ctx, cacheGroupKey, cacheKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, cacheGroupKey, cacheKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetCacheData provides a mock function with given fields: ctx, cacheGroupKey, cacheKey, value, exp
func (_m *DB) SetCacheData(ctx context.Context, cacheGroupKey string, cacheKey string, value []byte, exp time.Duration) error {
	ret := _m.Called(ctx, cacheGroupKey, cacheKey, value, exp)

	if len(ret) == 0 {
		panic("no return value specified for SetCacheData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []byte, time.Duration) error); ok {
		r0 = rf(ctx, cacheGroupKey, cacheKey, value, exp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDB creates a new instance of DB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *DB {
	mock := &DB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
