sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/**/__tests__/**/**, **/__tests__/**, pkg/**/__tests__/**/**

sonar.coverage.exclusions=**/*_test.go,**/mocks/**,**/*mock*.go
sonar.cpd.exclusions=**/*_test.go,**/mocks/**,**/*mock*.go,**/internal/test/**
