# Define the same root directory for sources and tests
 sonar.sources = src/
 sonar.tests = src/

 # Include test subdirectories in test scope
 sonar.test.inclusions = src/**/test/**/*

 # Exclude test subdirectories from source scope
 sonar.exclusions = src/**/test/**/*