// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PasswordHashing is an autogenerated mock type for the PasswordHashing type
type PasswordHashing struct {
	mock.Mock
}

// CompareHashedPassword provides a mock function with given fields: hashedString, input
func (_m *PasswordHashing) CompareHashedPassword(hashedString string, input string) bool {
	ret := _m.Called(hashedString, input)

	if len(ret) == 0 {
		panic("no return value specified for CompareHashedPassword")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(hashedString, input)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Hashing provides a mock function with given fields: input
func (_m *PasswordHashing) Hashing(input string) string {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for Hashing")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewPasswordHashing creates a new instance of PasswordHashing. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPasswordHashing(t interface {
	mock.TestingT
	Cleanup(func())
}) *PasswordHashing {
	mock := &PasswordHashing{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
