// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// HealthCheckRepository is an autogenerated mock type for the HealthCheckRepository type
type HealthCheckRepository struct {
	mock.Mock
}

// HealthCheck provides a mock function with given fields: ctx
func (_m *HealthCheckRepository) HealthCheck(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for HealthCheck")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewHealthCheckRepository creates a new instance of HealthCheckRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHealthCheckRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *HealthCheckRepository {
	mock := &HealthCheckRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
