// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// GenId is an autogenerated mock type for the GenId type
type GenId struct {
	mock.Mock
}

// GenerateId provides a mock function with no fields
func (_m *GenId) GenerateId() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateId")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewGenId creates a new instance of GenId. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGenId(t interface {
	mock.TestingT
	Cleanup(func())
}) *GenId {
	mock := &GenId{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
