// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ShortenUrl is an autogenerated mock type for the ShortenUrl type
type ShortenUrl struct {
	mock.Mock
}

// GetLinkFromCode provides a mock function with given fields: ctx, urlCode
func (_m *ShortenUrl) GetLinkFromCode(ctx context.Context, urlCode string) (string, error) {
	ret := _m.Called(ctx, urlCode)

	if len(ret) == 0 {
		panic("no return value specified for GetLinkFromCode")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, urlCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, urlCode)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, urlCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ShortenUrlWithExpiringTime provides a mock function with given fields: ctx, url, expireTime
func (_m *ShortenUrl) ShortenUrlWithExpiringTime(ctx context.Context, url string, expireTime int) (string, error) {
	ret := _m.Called(ctx, url, expireTime)

	if len(ret) == 0 {
		panic("no return value specified for ShortenUrlWithExpiringTime")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) (string, error)); ok {
		return rf(ctx, url, expireTime)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) string); ok {
		r0 = rf(ctx, url, expireTime)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, url, expireTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewShortenUrl creates a new instance of ShortenUrl. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShortenUrl(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShortenUrl {
	mock := &ShortenUrl{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
