definitions:
  bookmark.addBookmarkInput:
    properties:
      description:
        example: Google
        maxLength: 255
        type: string
      url:
        example: https://www.google.com
        maxLength: 2048
        type: string
    required:
    - url
    type: object
  bookmark.putBookmarkInput:
    properties:
      description:
        type: string
      url:
        type: string
    required:
    - description
    - url
    type: object
  model.Bookmark:
    properties:
      code:
        type: string
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      updated_at:
        type: string
      url:
        type: string
    type: object
  model.User:
    properties:
      created_at:
        type: string
      display_name:
        type: string
      email:
        type: string
      id:
        type: string
      updated_at:
        type: string
      username:
        type: string
    type: object
  url.shortenUrlRequest:
    properties:
      exp:
        type: integer
      url:
        type: string
    required:
    - exp
    - url
    type: object
  user.editInput:
    properties:
      display_name:
        type: string
      email:
        type: string
    required:
    - display_name
    - email
    type: object
  user.loginInput:
    properties:
      password:
        minLength: 8
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  user.registerInput:
    properties:
      display_name:
        type: string
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - display_name
    - email
    - password
    - username
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for bookmark management
  title: Bookmark API
  version: "3.0"
paths:
  /health-check:
    get:
      description: ping and pong with redis server
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: check redis health
      tags:
      - health check
  /v1/bookmarks:
    get:
      consumes:
      - application/json
      description: get lists of bookmarks of current user
      parameters:
      - default: 1
        description: page
        format: int32
        in: query
        name: page
        type: integer
      - default: 20
        description: limit
        format: int32
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              data:
                items:
                  $ref: '#/definitions/model.Bookmark'
                type: array
            type: object
      security:
      - BearerAuth: []
      summary: get lists of bookmarks of current user
      tags:
      - bookmark
    post:
      consumes:
      - application/json
      description: Create a new bookmark for a bookmark group
      parameters:
      - description: Input required
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/bookmark.addBookmarkInput'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            properties:
              data:
                $ref: '#/definitions/model.Bookmark'
              message:
                type: string
            type: object
      security:
      - BearerAuth: []
      summary: Create a new bookmark for a bookmark group
      tags:
      - bookmark
  /v1/bookmarks/{id}:
    delete:
      consumes:
      - application/json
      description: delete bookmark of id of current user
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              data:
                items:
                  $ref: '#/definitions/model.Bookmark'
                type: array
            type: object
      security:
      - BearerAuth: []
      summary: delete bookmark of id of current user
      tags:
      - bookmark
    put:
      consumes:
      - application/json
      description: edit bookmark of current user
      parameters:
      - description: Input required
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/bookmark.putBookmarkInput'
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              data:
                items:
                  $ref: '#/definitions/model.Bookmark'
                type: array
            type: object
      security:
      - BearerAuth: []
      summary: edit bookmark of current user
      tags:
      - bookmark
  /v1/links/redirect/{code}:
    get:
      consumes:
      - application/json
      parameters:
      - description: code
        in: path
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "302":
          description: Found
      summary: Redirect Forward the request to the original url
      tags:
      - url
  /v1/links/shorten:
    post:
      consumes:
      - application/json
      parameters:
      - description: Shorten URL Input payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/url.shortenUrlRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: receive the url, return the code
      tags:
      - url
  /v1/self/info:
    get:
      consumes:
      - applicatin/json
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            properties:
              data:
                $ref: '#/definitions/model.User'
            type: object
      security:
      - BearerAuth: []
      summary: get your current user information
      tags:
      - user
    put:
      consumes:
      - application/json
      description: edit your current user info
      parameters:
      - description: Input required
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/user.editInput'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            properties:
              message:
                type: string
            type: object
      security:
      - BearerAuth: []
      summary: edit your current info
      tags:
      - user
  /v1/users/login:
    post:
      consumes:
      - application/json
      description: Return a jwt toke if the input is correct
      parameters:
      - description: Input required
        in: body
        name: input
        schema:
          $ref: '#/definitions/user.loginInput'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            properties:
              data:
                type: string
              message:
                type: string
            type: object
      summary: return a jwt token if the input is correct
      tags:
      - user
  /v1/users/register:
    post:
      consumes:
      - application/json
      description: Create a new user
      parameters:
      - description: User registration input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/user.registerInput'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            properties:
              data:
                $ref: '#/definitions/model.User'
              message:
                type: string
            type: object
      summary: Create a netype createUser struct {
      tags:
      - user
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
