name: cd-pipeline

on:
  workflow_run:
    workflows: ['ci-pipeline']
    types: ['completed']

jobs:
  cd_pipeline:
    runs-on: self-hosted
    steps:
      - name: Deploy
        working-directory: /root/go-deployment
        run: |
          docker rm -f bookmark_service || true
          docker image rm viettrung21/bookmark-service:dev || true
          docker compose pull bookmark_service
          docker compose up -d bookmark_service
          docker image prune -f
      
