name: cd-pipeline

on:
  workflow_run:
    workflows: ['ci-pipeline']
    types: ['completed']

jobs:
  cd_pipeline:
    runs-on: self-hosted
    steps:
      - name: Deploy
        working-directory: /root/go-deployment
        run: |
          docker compose pull
          docker compose up -d --force-recreate
          docker image prune -f
      
